### ISSUE TITLE
Conver the CRUD_App  to School Management App

### ISSUE THREAD

**Issue by tukoba-dnyanoba1275** [tukoba-dnyanoba1275/Django-Projects#4]
### We want to convert the CRUD_App to A School Management App.
If anybody can, please do.

**Comment by vijay-jadhav1997** [comment]
Yes, I can.

**Comment by vijay-jadhav1997** [comment]
🤔 Could I remove the CRUD App and build a new School App using all the code of the CRUD App?

**Comment by tukoba-dnyanoba1275** [comment]
> 🤔 Could I remove the CRUD App and build a new School App using all the code of the CRUD App?

Sure. 
Do however you want to go ahead, but other Apps must not be affected by your code.

**Comment by tukoba-dnyanoba1275** [comment]
Great! 
I am going to merge your pull request right now

**Comment by tukoba-dnyanoba1275** [comment]
### Thanks @vijay-jadhav1997 for your valuable contribution.
